### ISSUE TITLE
Endpoint for sending car battery status

### ISSUE THREAD

**Issue by TomTorger** [Danielhiversen/pyTibber#118]
I use Home Assistant, have an Easee charger, but, unfortunately, a Nissan Leaf. This car is not supported for integration towards Tibber and, hence, the smart charging functionality isn't very smart. Could we use this library to send car battery status updates to Tibber? If so, we could allow Home assistant to send battery updates and thereby allow for an arbitrary car integration?

Or, perhaps, we could get access to the algorithm and the smartcharging ourselves :-)

**Comment by Danielhiversen** [comment]
Not supported by the Tibber API
