### ISSUE TITLE
Feature request: Energy consumption for Tibber customers using emeters

### ISSUE THREAD

**Issue by p1ranha** [Danielhiversen/pyTibber#120]
Hi,

would it be possible to include the energy consumption for customers of Tibber that do not use Pulse but have Discovergy meters installed?
I can see my consumption in the Tibber app, and with the new energy feature of HA, it would be very useful to see it directly in the intergration.

**Comment by Danielhiversen** [comment]
It is already supported by this library: https://github.com/Danielhiversen/pyTibber/blob/master/tibber/__init__.py#L677
(But not supported in HA)
