### ISSUE TITLE
Hardcoded offpeak

### ISSUE THREAD

**Issue by frafall** [Danielhiversen/pyTibber#152]
Offpeak is hard coded in code to 20:00 - 08:00 in current_attributes (unless I misread the code), probably should be configurable settings somehow as at least in Norway we will get 22:00 - 06:00 as off peak? (Nye nettleien som er litt utsatt).

Mvh
Morten

**Comment by Danielhiversen** [comment]
It follows the definition from Nordpool.
![image](https://user-images.githubusercontent.com/650502/147287300-739f95b6-5359-4c92-8044-520f04fc879b.png)
