### ISSUE TITLE
await' outside function

### ISSUE THREAD

**Issue by larsvinc** [Danielhiversen/pyTibber#159]
First - thank you for a great contribution to python and HA! Love it!

Second - I realize that this is not an issue, more a complex feature request / discussion across HA and this library?

I want to use the day-a-head pricing from Tibber to optimize the heating of my cabin (to keep it free of frost) during the winter. Specifically, it turns out that heating the cabin at night can save a lot of money by avoiding peak-pricing.

It does however turn out that there are signficant day-to-day variations, and as such I need to tailor the heating to the specific pricing for each day. So I want to pull the day-a-head in the evening. Ideally this would be a attribute in Home Assistant that I could pass on to a python script. I don't know how that would look as an attribute? Perhaps an array for hours 0-23?

My alternative is to pull the data myself directly in the python script. Trying to run the example in a simple script I get this feedback:
SyntaxError: 'await' outside function

I realize that this is probably to the lack of async, and I am not a very experienced programmer (have contributed to HA though :)). But is it possible to use the library synchronously to pull the day-a-head once?

**Comment by kaar** [comment]
You need an event loop

Simple async loop example
```py
import asyncio


async def main():
    print('your async code here')


if __name__ ==  '__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())
```

Example from README with async loop
```py
import tibber
import asyncio


async def main():
    access_token = tibber.DEMO_TOKEN
    tibber_connection = tibber.Tibber(access_token)
    await tibber_connection.update_info()
    print(tibber_connection.name)

    home = tibber_connection.get_homes()[0]
    await home.update_info()
    print(home.address1)

    await home.update_price_info()
    print(home.current_price_info)

    await tibber_connection.close_connection()


if __name__ ==  '__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())
```

**Comment by larsvinc** [comment]
@kaar Thanks! Works like a charm. You could consider including this in the readme.md to make it more accessible to other noobs like me.

I would welcome a discussion about including the day-a-head in HA because I believe it will be crucial in future algorithms for energy optimization. But perhaps this issue-tracker is not the place to have that discussion :)
