### ISSUE TITLE
[Feature equest] Add statistics for the cost/energy to be used in the HA energy dashboard

### ISSUE THREAD

**Issue by seagri** [Danielhiversen/pyTibber#179]
Not sure if this is supported in pyTibber aleady or maybe it should be implemented in HA directly,

Today we have the this for the tibber integration in home assistant(HA)

Once a day a statistics with hourly consumption and cost data is generated that can be used in the [Energy Dashboard](https://www.home-assistant.io/docs/energy/). (The ids are tibber:energy_consumption_HOMEID and tibber:energy_totalcost_HOMEID )

It would be nice to see the "cost/money per kWh" that day/week/month and so on.
Today the tibber:energy_totalcost_HOMEID includes the monthly fee. Maybe this can be discussed if it should be included in this statistic or not.

It could look something like this maybe:
![1afdbc3140ecf29ef524b39a43714f91b2d6972e](https://user-images.githubusercontent.com/12122654/172374172-40a55e06-346e-4a12-bcb4-4f15985bab30.png)
When looking at the energy dashboard in HA

**Comment by Danielhiversen** [comment]
Not relevant for this repo.
Home Assistant feature request should be added here https://community.home-assistant.io/c/feature-requests/13
