### ISSUE TITLE
Realtime power

### ISSUE THREAD

**Issue by peroveh** [Danielhiversen/pyTibber#183]
Hi... I am trying to read out single (or few) realtime samples of instantaneous power from python.  I am uncertain about how to use the (now) pure async examples in a three stage process  where I
1) read a few  power samples, with time
2) Turn on a relay
3) read a few power sampls again.

This appears a bit tricky to do with the demonstrated asyncio streaming examples..
Is there a way to do single shot http request for example?

**Comment by Danielhiversen** [comment]
> Is there a way to do single shot http request for example?

No.
You need to stream the data.
