### ISSUE TITLE
Callback not called when using pytibber as docker container

### ISSUE THREAD

**Issue by marcelcastrobr** [Danielhiversen/pyTibber#210]
Hi,
 First thanks for this repo.
 I am running your "real time data" example as a docker container, but the callback does not get called therefore no data.
 The container is able to open the session and get_homes.
 
 I have another container that only get the "current_price_info" and this container works well in the same setup.
 I assume my issue is around the rt_subscribe using aiohttp websession for the setup that I have.
 Have you had such issue before?

 **Setup:**
python3.9.12
docker 20.10.21
docker host: Ubuntu 18.04.6 LTS

**requirements.txt:**
aiohttp==3.8.1
aiosignal==1.2.0
async-timeout==4.0.2
attrs==22.1.0
charset-normalizer==2.1.0
frozenlist==1.3.0
graphql-subscription-manager
idna==3.3
multidict==6.0.2
numpy==1.23.1
pandas==1.4.3
python-dateutil==2.8.2
pyTibber==0.25.6
boto3 >= 1.20.13
argparse
AWSIoTPythonSDK==1.5.2

I am able to run the realtime python script on the host machine without problem. 

Any help recommendation?

**Comment by marcelcastrobr** [comment]
What is interesting is that if I try to get realtime data using python_graphql_client, like in the example [here](https://developer.tibber.com/docs/guides/calling-api), it works.

**Comment by Danielhiversen** [comment]
Sorry, but not time to do support
