### ISSUE TITLE
Subscription does not work (callback not called)

### ISSUE THREAD

**Issue by ThomasRgbg** [Danielhiversen/pyTibber#218]
Hi, 
I'm trying to use the realtime data example out of the Readme.me. But the Callback function is never called, even when adding a sleep at the end.
However, when using the API explorer from Tibber, I get data. 
I noted at Tibbers documentation the "Breaking change in websocket subscriptions December 2022" description and here in pyTibber the old wss URL is still used. But it is not yet Dec 22, so should be not yet the problem I hope. 

Does anyone else have this code currently working ? 

EDIT: Changing the URL in SUB_ENDPOINT at https://github.com/Danielhiversen/pyTibber/blob/e764b973b48f513702ae050148e51f0f195f8542/tibber/__init__.py#L18 seems to fix the issue. 
and adding a "await asyncio.sleep(120) would also not hurt at the end of the example, since at least with my connection here the default timeout of 10 seconds seems to be a bit on the edge.

**Comment by Danielhiversen** [comment]
Sorry, but I do not have time to give support on this

**Comment by flopp999** [comment]
@ThomasRgbg 

Do you have a complete .py file where you can get Realtime data?
Maybe you can post it here, thanks

**Comment by ThomasRgbg** [comment]
Sorry for the late reply... it is a bit more, also writing then the data into a influxdb. It is a little bit hacked out of the examples and i did not spend a lot of time, but it worked. For the realtime measurements, I added some averaging to not blow the database to much.
-------

import asyncio

import aiohttp
import tibber

import dateutil
import datetime
import time

from influxdb_client import influxdb_cli

influxdb = influxdb_cli('192.168.0.0', 'user', 'pw', 'db')

power_average_seconds = 60
power_average_count = 0
power_average = 0
power_average_start_timestamp = datetime.datetime.now()
power_sum_seconds = 300 / power_average_seconds
power_sum_count = 0

def _callback(pkg):
    global power_average_seconds
    global power_average_count
    global power_average
    global power_average_start_timestamp
    global power_sum_seconds
    global power_sum_count

    data = pkg.get("data")
    if data is None:
        print("No Callback data none")
        return
    realtimedata = data.get("liveMeasurement")
    print('Realtime power={0}, powerProduction={1}'.format(realtimedata['power'],realtimedata['powerProduction']))
    power = realtimedata['power'] - realtimedata['powerProduction']

    dt_timestamp = dateutil.parser.parse(realtimedata['timestamp'])

    if power_average_count == 0:
        power_average = float(power)
        power_average_start_timestamp = datetime.datetime.now()
    else:
        power_average += power
    
    power_average_count += 1
    
    print(power_average_count, power_average, power_average_start_timestamp)
    
    if datetime.datetime.now() - power_average_start_timestamp > datetime.timedelta(seconds = power_average_seconds):
        power_sum = power_average / power_average_count
        power_average_count = 0
        power_sum_count += 1

        dt_timestamp = dateutil.parser.parse(realtimedata['timestamp'])
        influxdb.write_sensordata("grid_tibber", "meter_power", power_sum , dt_timestamp)

        if power_sum_count > power_sum_seconds:
            power_sum_count = 0
            influxdb.write_sensordata("grid_tibber", "meter_comsumption", realtimedata['lastMeterConsumption'] , dt_timestamp)
            influxdb.write_sensordata("grid_tibber", "meter_production", realtimedata['lastMeterProduction'] , dt_timestamp)
    
async def main():
    ACCESS_TOKEN = "myapikeywouldbehere"
    async with aiohttp.ClientSession() as session:
        tibber_connection = tibber.Tibber(ACCESS_TOKEN, websession=session)
        await tibber_connection.update_info()

        home = tibber_connection.get_homes()[0]
        await home.update_info()
        await home.update_price_info()
        
        #if not home.rt_subscription_running:
        await home.rt_subscribe(_callback)

        await asyncio.sleep(10)

        while(True):
            
            await home.update_info_and_price_info()

            prices = home.price_total

            for timestamp in prices:
               dt_timestamp = dateutil.parser.parse(timestamp)

               influxdb.write_sensordata("grid_tibber", "price_total", prices[timestamp] , dt_timestamp)

            await asyncio.sleep(60*30)


if __name__ == '__main__':
    asyncio.run(main())

**Comment by flopp999** [comment]
@ThomasRgbg Thanks I will try it

**Comment by flopp999** [comment]
@ThomasRgbg it worked fine after I added ", user_agent="user_agent" " and Tibber Demo Token

```
  ACCESS_TOKEN = "5K4MVS-OjfWhK_4yrjOlFe1F6kJXPVf7eQYggo8ebAE"
    async with aiohttp.ClientSession() as session:
        tibber_connection = tibber.Tibber(ACCESS_TOKEN, websession=session, user_agent="user_agent")

```
