### ISSUE TITLE
Working example for Realtime data

### ISSUE THREAD

**Issue by flopp999** [Danielhiversen/pyTibber#228]
Anyone have a complete example.py to get realtime data from "wss://websocket-api.tibber.com/v1-beta/gql/subscriptions"?

**Comment by Danielhiversen** [comment]
https://github.com/home-assistant/home-assistant/tree/dev/homeassistant/components/tibber

**Comment by flopp999** [comment]
That link is for HA.
I want an example for a single py file

**Comment by Danielhiversen** [comment]
That should work as an example.
You also have https://github.com/Danielhiversen/pyTibber#example-realtime-data

**Comment by flopp999** [comment]
That example gives me error for useragent even if I change text to the example that Tibber has on their page, "Homey/10.0.0 com.Tibber/1.8.3"
I also tried with other useragent but same error.
I can see in your code that user_agent is set to None, is that wrong?

**Comment by Danielhiversen** [comment]
Ahh, there bug introduced in https://github.com/Danielhiversen/pyTibber/pull/212

**Comment by alexbergsland** [comment]
> That example gives me error for useragent even if I change text to the example that Tibber has on their page, "Homey/10.0.0 com.Tibber/1.8.3" I also tried with other useragent but same error. I can see in your code that user_agent is set to None, is that wrong?

Did you get it running?
I get no output from the "Example realtime data".
