### ISSUE TITLE
Excessive logging from gql

### ISSUE THREAD

**Issue by heikkih** [Danielhiversen/pyTibber#234]
Hi.

I just upgraded to Home Assistant 2022.12, and it seems the usage of gql in #222 introduced some excessive info-logging of every websocket-payload. It spammed my log heavily, so I had to add a "gql.transport.websockets: warning" to my logger-setup.

Might be some inherited log.isEnabledFor(logging.INFO) somewhere.

The version of gql installed by default in Home Assistant Container (docker) is:
bash-5.1# pip show gql
Name: gql
Version: 3.4.0

Best regards
Heikki

**Comment by Danielhiversen** [comment]
Have you then enabled info logging in Home Assistant?

**Comment by Danielhiversen** [comment]
> this payload-logging should probably be debug

Agree 👍
