### ISSUE TITLE
pyTibber uses disabled websocket API

### ISSUE THREAD

**Issue by wolfc01** [Danielhiversen/pyTibber#242]
Hi Daniel,

during testing I discovered that this library does not use the new API. As of developer.tibber.com, the old websocket api has been switched off as of 4 january 14:00.

Please let me know if that oberservation is right. See also my remark at https://github.com/Danielhiversen/pyTibber/issues/240#issuecomment-1370955722

Br
Carl.

**Comment by alexbergsland** [comment]
I am sorry if this is a dumb question, but am I correct in understanding that pyTibber does now work until #213 is merged?
The real time data example returns nothing with my own ACCESS_TOKEN.

**Comment by Danielhiversen** [comment]
Fixed in https://github.com/Danielhiversen/pyTibber/releases/tag/0.27.0
