### ISSUE TITLE
AttributeError: 'Client' object has no attribute 'session'

### ISSUE THREAD

**Issue by stianja** [Danielhiversen/pyTibber#253]
Hi, I don't get rt_subsctibe to work with a fresh ubuntu docker container with pytibber and run the example code for realtime data. The problem seems to be related to the use of gql.client in this line of tibber_home.py:

`async for data in self._tibber_control.sub_manager.session.subscribe(`

When I catch the exception thrown here I get the message:

`AttributeError: 'Client' object has no attribute 'session'`

Whis seems to be correct. gql.client does not have a "session", but does have a "subscribe".

So, when I tried to fix the code to the following line:

`async for data in self._tibber_control.sub_manager.subscribe( # Removed .session.`

I got this exception:

`'async for' requires an object with __aiter__ method, got generator`  so I might be wrong with my assumptions.

So, is pyTibber dependent on a spesific/older version of gql since it uses .session? Or is the .session attribute generated when a successfull connection is established?

**Comment by Danielhiversen** [comment]
This was fixed in [0.26.12](https://github.com/Danielhiversen/pyTibber/compare/0.26.11...0.26.12)
But I have not had time to patch it to 0.27.X yet

**Comment by stianja** [comment]
Thanks for feedback. Did not get rt_subscribe 0.26.12 to run either. Hardcoded URL was not correct, and _callback was never called and could not figure out why. Anyway, inspired by your gql code as example I got my own little realtime2graphite script working after the December API change. Thanks, a cup of coffee is donated, keep up the great work

**Comment by sugarjo** [comment]
@stianja : are you willing to share your code?

**Comment by stianja** [comment]
> @stianja : are you willing to share your code?

@sugarjo  Sure, please hold on till I manage to rewrite the code to a publishable version :)
