### ISSUE TITLE
Looking for MicroPhyton or Arduino library for Tibber API

### ISSUE THREAD

**Issue by Fagge40** [Danielhiversen/pyTibber#262]
Is there anyone out there who has managed to request Subsctiption real time data, for ESP32 or similar small hardware?.

After the changes in websocket subscriptions...
I'm completely stuck. Even ChatGPT can't handle it.
Now it's up to you Daniel to save the world :)
/Greetings from Sweden

**Comment by Danielhiversen** [comment]
I have not tried
