### ISSUE TITLE
Found less data than requested

### ISSUE THREAD

**Issue by martin3000** [Danielhiversen/pyTibber#263]
From tibber_home.get_historic_data I get the warning "Found less data than requested".
I tried to understand the code, but I don't understand the role of "max_n_data = max_n_data // 10" in the loop.
It starts with 5000, then 500, 50, 5 and 0.
<strike>Also, the API returns the hierarchy viewer->homes->comsumption and not viewer->home->consumption, but maybe this is due to the fact that this integration uses the old API.</strike>

**Comment by Danielhiversen** [comment]
How much data did you request? (value of n_data) 
How much was returned?

**Comment by martin3000** [comment]
Sorry I forgot to mention that I use home assistant and home assistant uses pyTibber. I don't know how much data was requested.

**Comment by Danielhiversen** [comment]
Ok, it is only a warning. This code is changed in the next release of the library.
