### ISSUE TITLE
websockets.exceptions.ConnectionClosedError: received 4429 (private use) Too many open connections on this server: 

### ISSUE THREAD

**Issue by BastiR40** [Danielhiversen/pyTibber#265]
Yet the basic script is runnuing, but now i'm faced with another Problem:

`websockets.exceptions.ConnectionClosedError: received 4429 (private use) Too many open connections on this server: 2; then sent 4429 (private use) Too many open connections on this server: 2`

How can i get this under control ?

THX bastiR

**Comment by Danielhiversen** [comment]
Generate a new access token at https://developer.tibber.com/
