### ISSUE TITLE
python3.8 compatability, for Venos OS

### ISSUE THREAD

**Issue by rodwalker** [Danielhiversen/pyTibber#271]
I`d like to use the Tibber Pulse readings as the Victron Grid Meter in a similar way to
 https://github.com/RalfZim/venus.dbus-fronius-smartmeter
This would need pyTibber to run on the stripped down Venus OS, running on a Raspi. It has
Python 3.8.13 and some limited installable packages using opkg
Of course I can pip install packages, but only see an old version of pyTibber
# python -m pip show pyTibber
Name: pyTibber
Version: 0.21.7

I suppose there is some dependence on python3.9, but I don`t think it is possible to put python3.9 on VenusOS, at least not without breaking things.
I would be grateful for any help as to how to proceed. For example, is it feasible to make pyTibber compatible with python 3.8?

Cheers,
Rod,

**Comment by Danielhiversen** [comment]
Sorry, but I do not plan to support old versions of python.
