### ISSUE TITLE
realtime.sub_manager is None

### ISSUE THREAD

**Issue by bitte-ein-bit** [Danielhiversen/pyTibber#277]
I see a lot of these in my HA 2023.08.03 installation:

```
Logger: tibber.home
Source: /usr/local/lib/python3.11/site-packages/tibber/home.py:455 
First occurred: 02:52:49 (4485 occurrences) 
Last logged: 15:31:55

Error in rt_subscribe
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/tibber/home.py", line 433, in _start
    async for data in self._tibber_control.realtime.sub_manager.session.subscribe(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'session'
```

The connection is maybe working for one or two hours. Not sure if these relate to the existing tickets: https://github.com/home-assistant/core/issues/97970 or https://github.com/home-assistant/core/issues/97665

I'm checking if moving the assert or catching the Attribute error are viable options, but I must admit, the code has not fully opened up to me yet. ;-)

**Comment by Danielhiversen** [comment]
https://github.com/home-assistant/core/issues/97665#issuecomment-1680497462
