### ISSUE TITLE
Home_id not active, unable to pull info

### ISSUE THREAD

**Issue by alexhopes** [Danielhiversen/pyTibber#281]
While the code worked fine with the demo token, using my actual token did not work. When investigating further and comparing all key values pairs received, I noticed that my home id is "not active". How would I change that?

Both images for comparison.

DEMO:
<img width="511" alt="tibbernew_py_—_pw" src="https://github.com/Danielhiversen/pyTibber/assets/347975/1f7f3569-60d7-447b-9c6e-855fce832ee2">

REAL ACCOUNT:
![76bd7d12-eca2-4379-9f00-4e0c1450a5cb](https://github.com/Danielhiversen/pyTibber/assets/347975/abf616d2-71d6-4354-a320-6f0581101155)
In this screenshot you will see that the home id can be found, but does not show up as active. How to change that?

**Comment by Danielhiversen** [comment]
You need a Tibber subscription
