### ISSUE TITLE
Mehrere Instanzen 

### ISSUE THREAD

**Issue by wartungsmonteur** [Danielhiversen/pyTibber#290]
Hallo

Ist es möglich zwei Tibber Instanzen im Home-Assistenten laufen zu lassen ? Ich habe zwei Zähler die von Tibber beliefert werden und jeder mit einem Pulse perfekt kommuniziert.

Vielen Dank.

**Comment by Danielhiversen** [comment]
English please

**Comment by wartungsmonteur** [comment]
Hello

 Is it possible to run two Tibber instances in the Home Assistant?  I have two meters that are supplied by Tibber and each communicates perfectly with a Pulse.

 Thank you.
