### ISSUE TITLE
Missing matplotlib with HA Core version 2024.2.1

### ISSUE THREAD

**Issue by jatty** [Danielhiversen/pyTibber#291]
When upgrading from HA Core version 2023.2.0 to 2024.2.1 I get an error with tibber_custom:

Logger: homeassistant.setup
Source: setup.py:221
Setup failed for custom integration 'tibber_custom': Requirements for tibber_custom not found: ['matplotlib'].

**Comment by Danielhiversen** [comment]
https://github.com/Danielhiversen/home_assistant_tibber_custom/issues/53
