### ISSUE TITLE
Breaking change?

### ISSUE THREAD

**Issue by viktorgunnarson** [Danielhiversen/pyTibber#323]
I have the same issue as #321 .

From what I can find in the Tibber API documentation the old values are still present (called [PriceLevel](https://developer.tibber.com/docs/reference#pricelevel)) and the new values that comes through is what Tibber refers to as [PriceRatingLevel](https://developer.tibber.com/docs/reference#priceratinglevel). Is this change on the Tibber API side or something changed in this library?

**Comment by viktorgunnarson** [comment]
@Danielhiversen What was the original issue that you were solving with #317? If I want to look at contributing a fix for the breaking change it would be good info. :)

**Comment by Danielhiversen** [comment]
https://github.com/home-assistant/core/issues/125674
