### ISSUE TITLE
Away state from Tibber app

### ISSUE THREAD

**Issue by francisrath** [Danielhiversen/pyTibber#56]
I'd like to use the Tibber app to set the "away state" of my home, and then use this flag in Home Assistant to control other components in the house. As far as I can tell this is not exposed in the Tibber API, but you might know of a way to expose this?

If it could be implemented in the home assistant plugin it would be great :)

**Comment by Danielhiversen** [comment]
It is not exposed in the API, so it is currently not possible.
I will add support for it if it gets supported in the API

**Comment by francisrath** [comment]
I have talked to Tibber today, and they agree it's a good idea, and it will be implemented fairly shortly. Will be bidirectional (i.e. you can read the current state, and set a new state from the API) 🙌
