### ISSUE TITLE
Live Measurement

### ISSUE THREAD

**Issue by kimmilde** [Danielhiversen/pyTibber#60]
Hello. 

Not sure if its a issue or what but i'm trying to use rt_subscribe to get out live measurement, but i'm not sure what to put in the required fields loop and async_callback. Could you please help me?

**Comment by Danielhiversen** [comment]
Here you can see how it is used in Home Assistant:
https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/sensor/tibber.py#L177
