### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by AndreasMoe** [Danielhiversen/pyTibber#72]
Trying to run in pycharm, pytibber module loaded

Where should I put my access_token?
import tibber
tibber_connection = tibber.Tibber()  # access_token=YOUR_TOKEN
tibber_connection.sync_update_info()

How should this look?
import tibber
tibber_connection = tibber.Tibber()  
access_token='1314123123xxxxx' # like this? I still get Arya Stark when using this 
tibber_connection.sync_update_info()

**Comment by kribor** [comment]
I think this is it: 

```
access_token='bla'
tibber_connection = tibber.Tibber(access_token)
```
Bu then the api crashes instead after saying:```

  File "call.py", line 4, in <module>
    tibber_connection.sync_update_info()
  File "/home/kristofer/.local/lib/python3.6/site-packages/tibber/__init__.py", line 121, in sync_update_info
    loop.run_until_complete(task)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/home/kristofer/.local/lib/python3.6/site-packages/tibber/__init__.py", line 148, in update_info
    raise InvalidLogin(msg)
tibber.InvalidLogin: String cannot represent value: ["email@test.com", "my real name"]
```

**Comment by Danielhiversen** [comment]
`tibber_connection = tibber.Tibber(access_token='YOUR_TOKEN')`
