### ISSUE TITLE
current power sensor is unavailable

### ISSUE THREAD

**Issue by magiva** [Danielhiversen/pyTibber#87]
ive had this issue before and it was simply a reboot of the whole pi to get it back up but ive tried rebooting over and over for a few days and nothing is getting this sensor back on.
HA is fully upto date with nothing pending
logs dont say anything either, i have it set for debug
2020-08-10 16:18:04 DEBUG (MainThread) [homeassistant.components.tibber.sensor] Asking for new data
thats the only thing is says for debug.

**Comment by Danielhiversen** [comment]
Does not seem related to this library. Would anyway need more debug info
