### ISSUE TITLE
"Timed out when connecting to Tibber"

### ISSUE THREAD

**Issue by hwestman** [Danielhiversen/pyTibber#88]
Integration is working, and im not bothered by this, but it seems to throw `Timed out when connecting to Tibber` on a regular basis in my installation. 

Just to give you an impression, 15-20 each day: 
![image](https://user-images.githubusercontent.com/1140735/93805825-86584c80-fc48-11ea-825e-c1605a1cee74.png)

Im running Home assistant docker, and its been throwing these for the last few months. Let me know if you want some more details.

**Comment by Danielhiversen** [comment]
Is your Internet connection working?

**Comment by hwestman** [comment]
It seem to work as it should. Attaching some monitoring of my latency and activity for the past 12 hours.

<img width="1710" alt="Screenshot 2020-09-24 at 00 06 35" src="https://user-images.githubusercontent.com/1140735/94074911-76806a00-fdfa-11ea-9ff9-60a3c624b459.png">

Here are some of the recent timeouts:

<img width="1409" alt="Screenshot 2020-09-24 at 00 06 51" src="https://user-images.githubusercontent.com/1140735/94074951-8d26c100-fdfa-11ea-8d28-8143dbe4c17a.png">


The timing of the timeouts are conspicuous though. I'm gonna look around to see if i'm doing any cron's or the like that might affect it.

**Comment by Danielhiversen** [comment]
The Tibber servers are a bit overloaded each hour.
I will do some modifications to spread the load more.

**Comment by hwestman** [comment]
Sounds good!

**Comment by Danielhiversen** [comment]
The first fix: https://github.com/home-assistant/core/pull/40787
(I will probably do one more fix)

**Comment by hwestman** [comment]
Awesome! I’ll confirm it when it’s out

**Comment by Danielhiversen** [comment]
Another fix: https://github.com/home-assistant/core/pull/40797
Will be part of HA 0.117
